use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMCategoryVCManager_Example' do
  pod 'AHFMCategoryVCManager', :path => '../'

  target 'AHFMCategoryVCManager_Tests' do
    inherit! :search_paths

    
  end
end
